name: Deploy to Lolipop via WebDAV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Test WebDAV connection
        run: |
          echo "Testing WebDAV connection..."
          curl -v -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -X OPTIONS \
               "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/" || true

      - name: Create necessary directories
        run: |
          echo "Creating directories..."
          curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -X MKCOL \
               "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/assets/" || true
          curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -X MKCOL \
               "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/assets/images/" || true

      - name: Deploy via WebDAV with curl
        run: |
          echo "Listing files to upload:"
          find ./out -type f

          # First upload index.html to test
          echo "Testing with index.html first..."
          curl -v -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -T "./out/index.html" \
               "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/index.html"

          # Then upload all files
          find ./out -type f | while read file; do
            remote_path="${file#./out/}"
            echo "Uploading $file to $remote_path"

            # Create directory structure if needed
            dir_path=$(dirname "$remote_path")
            if [ "$dir_path" != "." ]; then
              curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                   -X MKCOL \
                   "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/$dir_path/" || true
            fi

            response=$(curl -sS -w "%{http_code}" -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                 -T "$file" \
                 "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/$remote_path")
            echo "Upload response: $response"
          done

          if [ -f ".htaccess" ]; then
            echo "Uploading .htaccess"
            curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                 -T ".htaccess" \
                 "https://staba-mahounogakuen.webdav-lolipop.jp/mahounogakuen/.htaccess"
          fi

          